### ISSUE TITLE
Issue with running the container

### ISSUE THREAD

**Issue by rajuadduri** [voges/compass-docker#1]
Thank you for providing the docker setup for compass. I wish I am allowed to give you more than one star.
I have built the docker image using the following command from a directory containing Dockerfile, entrypoint.sh, install_compass.sh, and install_cplex.expect.

`docker build -t username/campass:latest`

I tried to run the container using the following command from a directory containing expression.tsv (the example file from the developers) and got an error.

`docker run username/campass:latest --data expression.tsv `

This gave the following error.

**usage: Compass [-h] [--data FILE] [--data-mtx FILE [FILE ...]] [--model MODEL]
               [--species SPECIES] [--media MEDIA] [--output-dir DIR]
               [--temp-dir DIR] [--torque-queue QUEUE] [--num-processes N]
               [--lambda F] [--num-threads N] [--and-function FXN]
               [--select-reactions FILE] [--select-subsystems FILE]
               [--num-neighbors N] [--symmetric-kernel] [--input-weights FILE]
               [--penalty-diffusion MODE] [--no-reactions]
               [--calc-metabolites] [--precache] [--input-knn FILE]
               [--input-knn-distances FILE] [--output-knn FILE]
               [--latent-space FILE] [--only-penalties] [--example-inputs]
               [--microcluster-size C] [--microcluster-file FILE]
               [--microcluster-data-file FILE] [--anndata-output]
               [--isoform-summing MODE] [--list-genes FILE]
               [--list-reactions FILE]
Compass: error: Nothing selected to do. Add arguments --data, --data-mtx, --precache, --list-genes, --list-reactions, or --example-inputs for Compass to do something.**

Can you help me find out what went wrong?

**Comment by voges** [comment]
Hey! Thanks for finding that bug. I forgot to forward the command line arguments to Compass inside the container. I just pushed a fix on the main branch. Please try again.

**Comment by rajuadduri** [comment]
Thanks Adam for sharing the bug fix.
It ran but threw an error with the example file.
Here is the error.

`docker run compass --data expression.tsv --species homo_sapiens --num-processes 10 --temp-dir DIR`

Building up model cache
100%|██████████| 4849/4849 [34:41<00:00,  2.33it/s]
100%|██████████| 10211/10211 [37:19<00:00,  4.56it/s]
Evaluating Reaction Penalties...
Traceback (most recent call last):
  File "/work/.venv/bin/compass", line 33, in <module>
    sys.exit(load_entry_point('compass-sc==0.9.10.2', 'console_scripts', 'compass')())
  File "/work/.venv/lib/python3.10/site-packages/compass/main.py", line 588, in entry
    penalties = eval_reaction_penalties(args['data'], args['model'],
  File "/work/.venv/lib/python3.10/site-packages/compass/compass/penalties.py", line 60, in eval_reaction_penalties
    expression = utils.read_data(expression_file) #pd.read_csv(expression_file, sep='\t', index_col=0)
  File "/work/.venv/lib/python3.10/site-packages/compass/utils.py", line 60, in read_data
    return pd.read_csv(data[0], sep='\t', index_col=0)
  File "/work/.venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/work/.venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/work/.venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/work/.venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/work/.venv/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/work/expression.tsv'

The persists even if I omit `--temp-dir` argument, and when I specify absolute path of `expression.tsv`

**Comment by voges** [comment]
The issue occurs because the `expression.tsv` file is not being mounted into the Docker container. By default, Docker containers do not have access to files from your host system. You need to mount a directory from your host into the container with the `-v|--volume` option to interact with files from your host system.

For example, if the `expression.tsv` file is in the current directory:

```sh
docker run --volume $(pwd):/data compass \
    --data /data/expression.tsv \
    --species homo_sapiens \
    --output-dir /data
```

**Comment by voges** [comment]
FYI: I will also add this info to the Readme.

**Comment by voges** [comment]
I have updated the Readme file. Also, I have improved the installation process.
